name: Flutter

packages:
  - apps/**
  - packages/**

scripts:
  build:pokemon:
    run: |
      cd apps/pokemon
      flutter pub run build_runner build --delete-conflicting-outputs

  build:state_management:
    run: |
      cd apps/state_management
      flutter pub run build_runner build --delete-conflicting-outputs

  run:pokemon:
    run: |
      cd apps/pokemon
      flutter run -d Android

  run:state_management:
    run: |
      cd apps/state_management
      flutter run -d chrome

  run:hook_routing:
    run: |
      cd apps/hook_routing
      flutter run -d chrome

  clean_run:pokemon:
    run: |
      cd apps/pokemon
      flutter pub run build_runner build --delete-conflicting-outputs
      flutter run -d Android

  clean_run:state_management:
    run: |
      cd apps/state_management
      flutter pub run build_runner build --delete-conflicting-outputs
      flutter run -d chrome

  analyze: melos exec -- "dart analyze ."
